[workspace]
members = [
	"packages/*",
    "examples/core/*",
    "examples/demos/*",
    "examples/comprehensive/*",
    "examples/website/*",
    # "website",
]
resolver = "2"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
