[package]
name = "perseus-actix-web"
version = "0.4.0-beta.13"
edition = "2021"
description = "An integration that makes the Perseus frontend framework easy to use with Actix Web."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/framesurge/perseus"
homepage = "https://framesurge.sh/perseus"
readme = "./README.md"
keywords = ["wasm", "frontend", "webdev", "ssg", "ssr"]
categories = ["wasm", "web-programming::http-server", "development-tools", "asynchronous", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../perseus", version = "0.4.0-beta.13" }
actix-web = "4.2"
actix-files = "0.6"
futures = "0.3"

[features]
# Enables the default server configuration, which provides a convenience function if you're not adding any extra routes
dflt-server = []
