[package]
name = "perseus-actix-web"
version = "0.1.1"
edition = "2018"
description = "An integration that makes the Perseus frontend framework easy to use with Actix Web."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "../../README.md"
keywords = ["wasm", "frontend", "webdev", "ssg", "ssr"]
categories = ["wasm", "web-programming::http-server", "development-tools", "asynchronous", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../perseus", version = "0.1.1" }
actix-web = "3.3"
actix-files = "0.5"
urlencoding = "2.1"
serde_json = "1"
error-chain = "0.12"
futures = "0.3"
sycamore = { version = "0.5.1", features = ["ssr"] }
