[package]
name = "perseus-cli"
version = "0.3.0-beta.20"
edition = "2018"
description = "The CLI for the Perseus frontend framework."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "./README.md"
keywords = ["wasm", "cli", "webdev", "ssg", "ssr"]
categories = ["wasm", "development-tools", "asynchronous", "gui", "command-line-utilities"]
include = [
    "src/",
    "Cargo.toml",
    ".perseus/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.6"
thiserror = "1"
fmterr = "0.1"
cargo_toml = "0.9"
indicatif = "0.17.0-beta.1" # Not stable, but otherwise error handling is just about impossible
console = "0.14"
serde = "1"
serde_json = "1"
clap = { version = "=3.0.0-beta.5", features = ["color"] }
fs_extra = "1"

[lib]
name = "perseus_cli"

[[bin]]
name = "perseus"
path = "src/bin/main.rs"
