[package]
name = "perseus-cli"
version = "0.4.0-beta.11"
edition = "2021"
description = "The CLI for the Perseus frontend framework."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "./README.md"
keywords = ["wasm", "cli", "webdev", "ssg", "ssr"]
categories = ["wasm", "development-tools", "asynchronous", "gui", "command-line-utilities"]
include = [
    "src/",
    "Cargo.toml",
    ".perseus/",
    "README.proj.md"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.6"
thiserror = "1"
fmterr = "0.1"
cargo_toml = "0.9"
indicatif = "=0.17.0-beta.1" # Not stable, but otherwise error handling is just about impossible
console = "0.14"
serde = "1"
serde_json = "1"
clap = { version = "3.2", features = [ "color", "derive", "unstable-v4" ] }
fs_extra = "1"
tokio = { version = "1", features = [ "macros", "rt-multi-thread", "sync" ] }
warp = "0.3"
command-group = "1"
ctrlc = { version = "3.0", features = ["termination"] }
notify = "=5.0.0-pre.13"
futures = "0.3"
tokio-stream = "0.1"
reqwest = { version = "0.11", features = [ "json", "stream" ] }
tar = "0.4"
flate2 = "1"
directories = "4"
cargo_metadata = "0.15"
cargo-lock = "8"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "2"

[lib]
name = "perseus_cli"

[[bin]]
name = "perseus"
path = "src/bin/main.rs"
