contact_links:
    - name: Create your issue with Tribble
      url: https://framesurge.sh/perseus/tribble/workflow/perseus/
      about: Perseus manages all contributions through Tribble now, try it out!
    - name: Ask a question about Perseus and Sycamore
      url: https://discord.com/invite/GNqWYWNTdp
      about: Join us on the Sycamore's Discord server.
    - name: Ask a general question
      url: https://github.com/framesurge/perseus/discussions/new
      about: Open a discussion.
