[package]
name = "perseus-example-tiny"
version = "0.3.0-beta.6"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../../packages/perseus" }
sycamore = "0.6"
